on: push

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $PASS
          echo $FIRST_NAME
        env:
          FIRST_NAME: ${{ secrets.USERNAME }}
          PASS: ${{ secrets.PASS }}
          LAST_NAME: Octocat
