# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tagName:
        description: "tag"
        required: true
        type: choice
        options:
          - "latest"
      env:
        description: "環境"
        required: true
        type: choice
        options:
          - "dev"
          - "stg"
          - "prd"

jobs:
  set-env:
    name: "www"
    runs-on: ubuntu-latest
    steps:
      - name: "eee"
        uses: actions/github-script@v6
        with:
          script: |
          
            context.payload = context.payload || {};
            const envs = {'dev': { name: 'dev', prefix: 'uuuuu'}, 'qa': { name: 'dev', prefix: 'dyyyy', acr: 'P'}};
            const inputs = context.payload.inputs;
            const temps = context.payload.inputs || {};
            const win = context.payload.inputs | {};
            let envData = null;
            
            console.log(inputs);
            console.log(inputs.tagName);
            console.log(context.payload.inputs);

            if( inputs.tagName ) {
              envData = envs
              console.log(envData);
              console.log(envData.prefix);
            }
            
            envData.acr = envData.acr ? envData.acr : envData.prefix;
            
            console.log(envData.acr);

