# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      env:
        description: "環境"
        required: true
        type: choice
        options:
          - "dev"
          - "stg"
          - "prd"

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script:
            echo "${{ context }}";
            echo "${{ context.payload }}";
            echo "${{ context.payload.inputs }}";
